// クイヤゲーム 収録データ
// n   : その語・記号が表す数
// t   : 難易度 (1=やさしい / 2=ふつう / 3=超難問用)
// rom : 読み・ローマ字表記
// kana: カタカナ読み（ヒントで表示）
// note: 豆知識（任意）
// 数字記号は字形の取り違えを避けるため Unicode エスケープで記述しています。
window.QIY_DATA = [
  // ───────── 難易度 1 ─────────
  { lang: "英語", text: "nine", kana: "ナイン", rom: "nine", n: 9, t: 1 },
  { lang: "英語", text: "eight", kana: "エイト", rom: "eight", n: 8, t: 1 },
  { lang: "ドイツ語", text: "neun", kana: "ノイン", rom: "noin", n: 9, t: 1, note: "「nein（いいえ）」とは別の単語。" },
  { lang: "ドイツ語", text: "zehn", kana: "ツェーン", rom: "tsehn", n: 10, t: 1 },
  { lang: "ドイツ語", text: "acht", kana: "アハト", rom: "acht", n: 8, t: 1 },
  { lang: "フランス語", text: "neuf", kana: "ヌフ", rom: "nœf", n: 9, t: 1, note: "「新しい」という意味もある同音異義語。" },
  { lang: "フランス語", text: "huit", kana: "ユイット", rom: "uit", n: 8, t: 1 },
  { lang: "フランス語", text: "dix", kana: "ディス", rom: "dis", n: 10, t: 1 },
  { lang: "スペイン語", text: "nueve", kana: "ヌエベ", rom: "nwebe", n: 9, t: 1 },
  { lang: "スペイン語", text: "ocho", kana: "オチョ", rom: "ocho", n: 8, t: 1 },
  { lang: "スペイン語", text: "siete", kana: "シエテ", rom: "siete", n: 7, t: 1 },
  { lang: "イタリア語", text: "nove", kana: "ノーヴェ", rom: "nove", n: 9, t: 1 },
  { lang: "イタリア語", text: "dieci", kana: "ディエチ", rom: "dieci", n: 10, t: 1 },
  { lang: "ポルトガル語", text: "oito", kana: "オイト", rom: "oitu", n: 8, t: 1 },
  { lang: "ポルトガル語", text: "dez", kana: "デイス", rom: "dez", n: 10, t: 1 },
  { lang: "オランダ語", text: "negen", kana: "ネーヘン", rom: "neːɣə(n)", n: 9, t: 1 },
  { lang: "オランダ語", text: "tien", kana: "ティーン", rom: "tin", n: 10, t: 1 },
  { lang: "スウェーデン語", text: "nio", kana: "ニーオ", rom: "nio", n: 9, t: 1 },
  { lang: "スウェーデン語", text: "tio", kana: "ティーオ", rom: "tio", n: 10, t: 1, note: "nio(9) と tio(10) は1文字違い。" },
  { lang: "ラテン語", text: "novem", kana: "ノウェム", rom: "novem", n: 9, t: 1, note: "November は古代ローマ暦で「9番目の月」だった。" },
  { lang: "ラテン語", text: "decem", kana: "デケム", rom: "dekem", n: 10, t: 1, note: "December の語源。古代ローマ暦では10番目の月。" },
  { lang: "ラテン語", text: "octo", kana: "オクトー", rom: "okto", n: 8, t: 1 },
  { lang: "ローマ数字", text: "IX", kana: "ノウェム", rom: "10 − 1", n: 9, t: 1 },
  { lang: "ローマ数字", text: "XI", kana: "ウンデキム", rom: "10 + 1", n: 11, t: 1 },
  { lang: "ローマ数字", text: "VIII", kana: "オクトー", rom: "5 + 3", n: 8, t: 1 },
  { lang: "中国語", text: "九", kana: "ジウ", rom: "jiǔ（ジウ）", n: 9, t: 1 },
  { lang: "中国語", text: "八", kana: "バー", rom: "bā（バー）", n: 8, t: 1 },
  { lang: "中国語", text: "六", kana: "リウ", rom: "liù（リウ）", n: 6, t: 1 },
  { lang: "中国語", text: "七", kana: "チー", rom: "qī（チー）", n: 7, t: 1 },
  { lang: "日本語", text: "ここのつ", kana: "ココノツ", rom: "kokonotsu", n: 9, t: 1 },
  { lang: "日本語", text: "やっつ", kana: "ヤッツ", rom: "yattsu", n: 8, t: 1 },
  { lang: "日本語", text: "きゅう", kana: "キュウ", rom: "kyū", n: 9, t: 1 },
  { lang: "日本語", text: "しち", kana: "シチ", rom: "shichi", n: 7, t: 1 },
  { lang: "韓国語", text: "아홉", kana: "アホプ", rom: "ahop（アホプ）", n: 9, t: 1 },
  { lang: "韓国語", text: "여덟", kana: "ヨドル", rom: "yeodeol（ヨドル）", n: 8, t: 1 },
  { lang: "韓国語", text: "열", kana: "ヨル", rom: "yeol（ヨル）", n: 10, t: 1 },
  { lang: "ロシア語", text: "девять", kana: "ジェーヴィチ", rom: "devyat'（ジェーヴィチ）", n: 9, t: 1 },
  { lang: "ロシア語", text: "десять", kana: "ジェーシチ", rom: "desyat'（ジェーシチ）", n: 10, t: 1, note: "девять(9) と десять(10) はそっくり。" },
  { lang: "ロシア語", text: "восемь", kana: "ヴォーシミ", rom: "vosem'（ヴォーシミ）", n: 8, t: 1 },
  { lang: "ギリシャ語", text: "εννέα", kana: "エネア", rom: "ennéa（エネア）", n: 9, t: 1 },
  { lang: "ギリシャ語", text: "οκτώ", kana: "オクト", rom: "októ（オクト）", n: 8, t: 1 },
  { lang: "ギリシャ語", text: "δέκα", kana: "デカ", rom: "déka（デカ）", n: 10, t: 1 },
  { lang: "ベトナム語", text: "chín", kana: "チン", rom: "chín（チン）", n: 9, t: 1 },
  { lang: "ベトナム語", text: "tám", kana: "ターム", rom: "tám（ターム）", n: 8, t: 1 },
  { lang: "インドネシア語", text: "sembilan", kana: "スンビラン", rom: "sembilan", n: 9, t: 1 },
  { lang: "インドネシア語", text: "delapan", kana: "ドゥラパン", rom: "delapan", n: 8, t: 1 },
  { lang: "トルコ語", text: "dokuz", kana: "ドクズ", rom: "dokuz", n: 9, t: 1 },
  { lang: "トルコ語", text: "sekiz", kana: "セキズ", rom: "sekiz", n: 8, t: 1 },
  { lang: "スワヒリ語", text: "tisa", kana: "ティサ", rom: "tisa", n: 9, t: 1 },
  { lang: "スワヒリ語", text: "saba", kana: "サバ", rom: "saba", n: 7, t: 1 },
  { lang: "スワヒリ語", text: "nane", kana: "ナネ", rom: "nane", n: 8, t: 1 },
  { lang: "タガログ語", text: "siyam", kana: "シヤム", rom: "siyam", n: 9, t: 1 },
  { lang: "タガログ語", text: "walo", kana: "ワロ", rom: "walo", n: 8, t: 1 },
  { lang: "エスペラント", text: "naŭ", kana: "ナウ", rom: "nau", n: 9, t: 1 },
  { lang: "エスペラント", text: "dek", kana: "デク", rom: "dek", n: 10, t: 1 },
  { lang: "ハワイ語", text: "ʻeiwa", kana: "エイワ", rom: "eiwa", n: 9, t: 1 },
  { lang: "ハワイ語", text: "ʻewalu", kana: "エヴァル", rom: "ewalu", n: 8, t: 1 },
  { lang: "タイ語", text: "เก้า", kana: "ガーオ", rom: "kâo（ガーオ）", n: 9, t: 1 },
  { lang: "タイ語", text: "แปด", kana: "ペート", rom: "bpàet（ペーット）", n: 8, t: 1 },
  { lang: "ヒンディー語", text: "नौ", kana: "ナウ", rom: "nau（ナウ）", n: 9, t: 1 },
  { lang: "ヒンディー語", text: "आठ", kana: "アート", rom: "āṭh（アート）", n: 8, t: 1 },
  { lang: "アラビア語", text: "تسعة", kana: "ティスア", rom: "tisʿa（ティスア）", n: 9, t: 1 },
  { lang: "アラビア語", text: "سبعة", kana: "サブア", rom: "sabʿa（サブア）", n: 7, t: 1, note: "تسعة(9) と سبعة(7) は点の位置が違うだけ。" },
  { lang: "アラビア文字の数字", text: "٩", kana: "ティスア", rom: "tisʿa", n: 9, t: 1 },
  { lang: "アラビア文字の数字", text: "٨", kana: "サマーニヤ", rom: "thamāniya", n: 8, t: 1 },
  { lang: "アラビア文字の数字", text: "٦", kana: "スィッタ", rom: "sitta", n: 6, t: 1 },

  // ───────── 難易度 2 ─────────
  { lang: "フィンランド語", text: "yhdeksän", kana: "ユフデクサン", rom: "yhdeksän", n: 9, t: 2 },
  { lang: "フィンランド語", text: "kahdeksan", kana: "カフデクサン", rom: "kahdeksan", n: 8, t: 2, note: "yhdeksän(9)とkahdeksan(8)は「10から1/2引く」が由来という説がある。" },
  { lang: "エストニア語", text: "üheksa", kana: "ユヘクサ", rom: "üheksa", n: 9, t: 2 },
  { lang: "エストニア語", text: "kaheksa", kana: "カヘクサ", rom: "kaheksa", n: 8, t: 2 },
  { lang: "ハンガリー語", text: "kilenc", kana: "キレンツ", rom: "kilents", n: 9, t: 2 },
  { lang: "ハンガリー語", text: "nyolc", kana: "ニョルツ", rom: "nyolts", n: 8, t: 2 },
  { lang: "ポーランド語", text: "dziewięć", kana: "ジェヴィェンチ", rom: "dźewjeńć", n: 9, t: 2 },
  { lang: "ポーランド語", text: "dziesięć", kana: "ジェシェンチ", rom: "dźeśeńć", n: 10, t: 2 },
  { lang: "チェコ語", text: "devět", kana: "デヴィェト", rom: "devjet", n: 9, t: 2 },
  { lang: "チェコ語", text: "deset", kana: "デセット", rom: "deset", n: 10, t: 2 },
  { lang: "ウクライナ語", text: "дев'ять", kana: "デヴャチ", rom: "dev'iat'", n: 9, t: 2 },
  { lang: "ウクライナ語", text: "вісім", kana: "ヴィシム", rom: "visim", n: 8, t: 2 },
  { lang: "ブルガリア語", text: "девет", kana: "デヴェト", rom: "devet", n: 9, t: 2 },
  { lang: "ブルガリア語", text: "десет", kana: "デセト", rom: "deset", n: 10, t: 2 },
  { lang: "クロアチア語", text: "devet", kana: "デヴェト", rom: "devet", n: 9, t: 2 },
  { lang: "クロアチア語", text: "osam", kana: "オサム", rom: "osam", n: 8, t: 2 },
  { lang: "リトアニア語", text: "devyni", kana: "デヴィーニ", rom: "devyni", n: 9, t: 2 },
  { lang: "リトアニア語", text: "dešimt", kana: "デシムト", rom: "dešimt", n: 10, t: 2 },
  { lang: "ラトビア語", text: "deviņi", kana: "デヴィニ", rom: "deviņi", n: 9, t: 2 },
  { lang: "ラトビア語", text: "astoņi", kana: "アストニ", rom: "astoņi", n: 8, t: 2 },
  { lang: "ルーマニア語", text: "nouă", kana: "ノウア", rom: "nowə", n: 9, t: 2 },
  { lang: "ルーマニア語", text: "zece", kana: "ゼチェ", rom: "zeche", n: 10, t: 2 },
  { lang: "カタルーニャ語", text: "nou", kana: "ノウ", rom: "nɔw", n: 9, t: 2, note: "「新しい」という意味もある。" },
  { lang: "カタルーニャ語", text: "vuit", kana: "ブイト", rom: "buit", n: 8, t: 2 },
  { lang: "アルバニア語", text: "nëntë", kana: "ネンテ", rom: "nëntë", n: 9, t: 2 },
  { lang: "アルバニア語", text: "tetë", kana: "テテ", rom: "tetë", n: 8, t: 2 },
  { lang: "アイルランド語", text: "naoi", kana: "ニー", rom: "niː", n: 9, t: 2 },
  { lang: "アイルランド語", text: "ocht", kana: "オクト", rom: "ocht", n: 8, t: 2 },
  { lang: "ウェールズ語", text: "naw", kana: "ナウ", rom: "nau", n: 9, t: 2 },
  { lang: "ウェールズ語", text: "wyth", kana: "ウイス", rom: "uith", n: 8, t: 2 },
  { lang: "ブルトン語", text: "nav", kana: "ナウ", rom: "nav", n: 9, t: 2 },
  { lang: "ブルトン語", text: "eizh", kana: "エイス", rom: "eis", n: 8, t: 2 },
  { lang: "アイスランド語", text: "níu", kana: "ニーウ", rom: "niːʏ", n: 9, t: 2 },
  { lang: "アイスランド語", text: "tíu", kana: "ティーウ", rom: "tʰiːʏ", n: 10, t: 2, note: "níu(9) と tíu(10) は1文字違い。" },
  { lang: "ノルウェー語", text: "ni", kana: "ニー", rom: "ni", n: 9, t: 2 },
  { lang: "ノルウェー語", text: "ti", kana: "ティー", rom: "ti", n: 10, t: 2 },
  { lang: "デンマーク語", text: "otte", kana: "オーデ", rom: "ode", n: 8, t: 2 },
  { lang: "アフリカーンス語", text: "nege", kana: "ネーヘ", rom: "neːχə", n: 9, t: 2 },
  { lang: "アフリカーンス語", text: "agt", kana: "アハト", rom: "aχt", n: 8, t: 2 },
  { lang: "バスク語", text: "bederatzi", kana: "ベデラツィ", rom: "bederatsi", n: 9, t: 2 },
  { lang: "バスク語", text: "zortzi", kana: "ソルツィ", rom: "sortsi", n: 8, t: 2 },
  { lang: "ジョージア語", text: "ცხრა", kana: "ツフラ", rom: "tskhra（ツフラ）", n: 9, t: 2 },
  { lang: "ジョージア語", text: "რვა", kana: "ルヴァ", rom: "rva（ルヴァ）", n: 8, t: 2 },
  { lang: "ジョージア語", text: "ათი", kana: "アティ", rom: "ati（アティ）", n: 10, t: 2 },
  { lang: "アルメニア語", text: "ինը", kana: "イヌ", rom: "inë（イヌ）", n: 9, t: 2 },
  { lang: "アルメニア語", text: "ութ", kana: "ウトゥ", rom: "utʿ（ウトゥ）", n: 8, t: 2 },
  { lang: "ヘブライ語", text: "תשע", kana: "テシャ", rom: "teshaʿ（テシャ）", n: 9, t: 2 },
  { lang: "ヘブライ語", text: "שבע", kana: "シェヴァ", rom: "shevaʿ（シェヴァ）", n: 7, t: 2 },
  { lang: "ペルシア語", text: "نه", kana: "ノフ", rom: "noh（ノフ）", n: 9, t: 2 },
  { lang: "ペルシア語", text: "هشت", kana: "ハシュト", rom: "hasht（ハシュト）", n: 8, t: 2 },
  { lang: "ペルシア文字の数字", text: "۹", kana: "ノフ", rom: "noh", n: 9, t: 2 },
  { lang: "ペルシア文字の数字", text: "۶", kana: "シェシュ", rom: "shesh", n: 6, t: 2 },
  { lang: "ウルドゥー語", text: "نو", kana: "ナウ", rom: "nau（ナウ）", n: 9, t: 2 },
  { lang: "ウルドゥー語", text: "آٹھ", kana: "アート", rom: "āṭh（アート）", n: 8, t: 2 },
  { lang: "クルド語", text: "neh", kana: "ネフ", rom: "neh", n: 9, t: 2 },
  { lang: "クルド語", text: "heşt", kana: "ヘシュト", rom: "hesht", n: 8, t: 2 },
  { lang: "サンスクリット", text: "नव", kana: "ナヴァ", rom: "nava（ナヴァ）", n: 9, t: 2 },
  { lang: "サンスクリット", text: "अष्ट", kana: "アシュタ", rom: "aṣṭa（アシュタ）", n: 8, t: 2 },
  { lang: "デーヴァナーガリー数字", text: "९", kana: "ナウ", rom: "nau", n: 9, t: 2 },
  { lang: "デーヴァナーガリー数字", text: "८", kana: "アート", rom: "āṭh", n: 8, t: 2 },
  { lang: "マラーティー語", text: "नऊ", kana: "ナウー", rom: "naū（ナウー）", n: 9, t: 2 },
  { lang: "ベンガル語", text: "নয়", kana: "ノイ", rom: "noy（ノイ）", n: 9, t: 2 },
  { lang: "ベンガル語", text: "আট", kana: "アト", rom: "aṭ（アト）", n: 8, t: 2 },
  { lang: "グジャラート語", text: "નવ", kana: "ナヴ", rom: "nav（ナヴ）", n: 9, t: 2 },
  { lang: "グジャラート語", text: "આઠ", kana: "アート", rom: "āṭh（アート）", n: 8, t: 2 },
  { lang: "パンジャーブ語", text: "ਨੌਂ", kana: "ナウン", rom: "nauṃ（ナウン）", n: 9, t: 2 },
  { lang: "パンジャーブ語", text: "ਅੱਠ", kana: "アット", rom: "aṭṭh（アット）", n: 8, t: 2 },
  { lang: "タミル語", text: "ஒன்பது", kana: "オンバドゥ", rom: "oṉpatu（オンバドゥ）", n: 9, t: 2 },
  { lang: "タミル語", text: "எட்டு", kana: "エットゥ", rom: "eṭṭu（エットゥ）", n: 8, t: 2 },
  { lang: "テルグ語", text: "తొమ్మిది", kana: "トンミディ", rom: "tommidi（トンミディ）", n: 9, t: 2 },
  { lang: "テルグ語", text: "ఎనిమిది", kana: "エニミディ", rom: "enimidi（エニミディ）", n: 8, t: 2 },
  { lang: "カンナダ語", text: "ಒಂಬತ್ತು", kana: "オンバットゥ", rom: "ombattu（オンバットゥ）", n: 9, t: 2 },
  { lang: "カンナダ語", text: "ಎಂಟು", kana: "エントゥ", rom: "eṇṭu（エントゥ）", n: 8, t: 2 },
  { lang: "マラヤーラム語", text: "ഒമ്പത്", kana: "オンバトゥ", rom: "ompatŭ（オンバトゥ）", n: 9, t: 2 },
  { lang: "マラヤーラム語", text: "എട്ട്", kana: "エットゥ", rom: "eṭṭŭ（エットゥ）", n: 8, t: 2 },
  { lang: "シンハラ語", text: "නවය", kana: "ナワヤ", rom: "navaya（ナワヤ）", n: 9, t: 2 },
  { lang: "シンハラ語", text: "අට", kana: "アタ", rom: "aṭa（アタ）", n: 8, t: 2 },
  { lang: "モンゴル語", text: "ес", kana: "ユス", rom: "yes（ユス）", n: 9, t: 2 },
  { lang: "モンゴル語", text: "найм", kana: "ナイム", rom: "naim（ナイム）", n: 8, t: 2 },
  { lang: "カザフ語", text: "тоғыз", kana: "トグズ", rom: "toğyz", n: 9, t: 2 },
  { lang: "カザフ語", text: "сегіз", kana: "セギズ", rom: "segiz", n: 8, t: 2 },
  { lang: "ウズベク語", text: "to'qqiz", kana: "トッキズ", rom: "toqqiz", n: 9, t: 2 },
  { lang: "ウズベク語", text: "sakkiz", kana: "サッキズ", rom: "sakkiz", n: 8, t: 2 },
  { lang: "アゼルバイジャン語", text: "doqquz", kana: "ドックズ", rom: "doqquz", n: 9, t: 2 },
  { lang: "アゼルバイジャン語", text: "səkkiz", kana: "セッキズ", rom: "säkkiz", n: 8, t: 2 },
  { lang: "ミャンマー語", text: "ကိုး", kana: "コー", rom: "kô（コー）", n: 9, t: 2 },
  { lang: "ミャンマー語", text: "ရှစ်", kana: "シッ", rom: "shiʔ（シッ）", n: 8, t: 2 },
  { lang: "ラオ語", text: "ເກົ້າ", kana: "カーオ", rom: "kao（カーオ）", n: 9, t: 2 },
  { lang: "ラオ語", text: "ແປດ", kana: "ペート", rom: "pèt（ペート）", n: 8, t: 2 },
  { lang: "クメール語", text: "ប្រាំបួន", kana: "プラムブオン", rom: "pram buən（プラム・ブオン）", n: 9, t: 2, note: "「5（プラム）＋4（ブオン）」という作り。" },
  { lang: "クメール語", text: "ប្រាំបី", kana: "プラムバイ", rom: "pram bei（プラム・バイ）", n: 8, t: 2, note: "「5＋3」という作り。" },
  { lang: "チベット語", text: "དགུ", kana: "グ", rom: "gu（グ）", n: 9, t: 2 },
  { lang: "チベット語", text: "བརྒྱད", kana: "ギェー", rom: "gyé（ギェー）", n: 8, t: 2 },
  { lang: "アムハラ語", text: "ዘጠኝ", kana: "ゼテニュ", rom: "zeṭeññ（ゼテニュ）", n: 9, t: 2 },
  { lang: "アムハラ語", text: "ስምንት", kana: "スミントゥ", rom: "sïmmïnt（スミントゥ）", n: 8, t: 2 },
  { lang: "ソマリ語", text: "sagaal", kana: "サガール", rom: "sagaal", n: 9, t: 2 },
  { lang: "ソマリ語", text: "siddeed", kana: "シッデード", rom: "siddeed", n: 8, t: 2 },
  { lang: "ハウサ語", text: "tara", kana: "タラ", rom: "tara", n: 9, t: 2 },
  { lang: "ハウサ語", text: "takwas", kana: "タクワス", rom: "takwas", n: 8, t: 2 },
  { lang: "ヨルバ語", text: "ẹ̀sán", kana: "エサン", rom: "ɛ̀sán", n: 9, t: 2 },
  { lang: "ヨルバ語", text: "ẹ̀jọ", kana: "エジョ", rom: "ɛ̀dʒɔ", n: 8, t: 2 },
  { lang: "イボ語", text: "itoolu", kana: "イトオル", rom: "itoolu", n: 9, t: 2 },
  { lang: "イボ語", text: "asatọ", kana: "アサト", rom: "asatɔ", n: 8, t: 2 },
  { lang: "コサ語", text: "lithoba", kana: "リトバ", rom: "litʰoba", n: 9, t: 2 },
  { lang: "コサ語", text: "sibhozo", kana: "シボゾ", rom: "sibɦozo", n: 8, t: 2 },
  { lang: "マダガスカル語", text: "sivy", kana: "シヴ", rom: "sivi", n: 9, t: 2 },
  { lang: "マダガスカル語", text: "valo", kana: "ヴァル", rom: "valu", n: 8, t: 2 },
  { lang: "マオリ語", text: "iwa", kana: "イワ", rom: "iwa", n: 9, t: 2 },
  { lang: "マオリ語", text: "waru", kana: "ワル", rom: "waru", n: 8, t: 2 },
  { lang: "サモア語", text: "iva", kana: "イヴァ", rom: "iva", n: 9, t: 2 },
  { lang: "サモア語", text: "valu", kana: "ヴァル", rom: "valu", n: 8, t: 2 },
  { lang: "トンガ語", text: "hiva", kana: "ヒヴァ", rom: "hiva", n: 9, t: 2 },
  { lang: "トンガ語", text: "fitu", kana: "フィトゥ", rom: "fitu", n: 7, t: 2 },
  { lang: "フィジー語", text: "ciwa", kana: "ズィワ", rom: "ðiwa", n: 9, t: 2 },
  { lang: "フィジー語", text: "walu", kana: "ワル", rom: "walu", n: 8, t: 2 },
  { lang: "ジャワ語", text: "sanga", kana: "ソンゴ", rom: "sɔŋɔ", n: 9, t: 2 },
  { lang: "ジャワ語", text: "wolu", kana: "ウォル", rom: "wolu", n: 8, t: 2 },
  { lang: "ケチュア語", text: "isqun", kana: "イスコン", rom: "isqun", n: 9, t: 2 },
  { lang: "ケチュア語", text: "pusaq", kana: "プサク", rom: "pusaq", n: 8, t: 2 },
  { lang: "中国語（大字）", text: "玖", kana: "ジウ", rom: "jiǔ", n: 9, t: 2, note: "改ざん防止のため小切手などで使う「大字」。" },
  { lang: "中国語（大字）", text: "捌", kana: "バー", rom: "bā", n: 8, t: 2 },
  { lang: "中国語（大字）", text: "柒", kana: "チー", rom: "qī", n: 7, t: 2 },
  { lang: "韓国語（漢数詞）", text: "구", kana: "ク", rom: "gu（ク）", n: 9, t: 2 },
  { lang: "韓国語（漢数詞）", text: "팔", kana: "パル", rom: "pal（パル）", n: 8, t: 2 },
  { lang: "韓国語（漢数詞）", text: "육", kana: "ユク", rom: "yuk（ユク）", n: 6, t: 2 },
  { lang: "タイ数字", text: "๙", kana: "ガーオ", rom: "kâo", n: 9, t: 2 },
  { lang: "タイ数字", text: "๘", kana: "ペート", rom: "bpàet", n: 8, t: 2 },

  // ───────── 難易度 3（超難問）─────────
  { lang: "ベンガル数字", text: "৯", kana: "ノイ", rom: "noy", n: 9, t: 3 },
  { lang: "ベンガル数字", text: "৪", kana: "チャル", rom: "car（チャル）", n: 4, t: 3, note: "8に見えるが「4」。" },
  { lang: "タミル数字", text: "௯", kana: "オンバドゥ", rom: "oṉpatu", n: 9, t: 3 },
  { lang: "タミル数字", text: "௮", kana: "エットゥ", rom: "eṭṭu", n: 8, t: 3 },
  { lang: "グジャラート数字", text: "૯", kana: "ナヴ", rom: "nav", n: 9, t: 3 },
  { lang: "グジャラート数字", text: "૮", kana: "アート", rom: "āṭh", n: 8, t: 3 },
  { lang: "オディア数字", text: "୯", kana: "ノ", rom: "na", n: 9, t: 3 },
  { lang: "オディア数字", text: "୮", kana: "アタ", rom: "āṭha", n: 8, t: 3 },
  { lang: "テルグ数字", text: "౯", kana: "トンミディ", rom: "tommidi", n: 9, t: 3 },
  { lang: "テルグ数字", text: "౮", kana: "エニミディ", rom: "enimidi", n: 8, t: 3 },
  { lang: "マラヤーラム数字", text: "൯", kana: "オンバトゥ", rom: "ompatŭ", n: 9, t: 3 },
  { lang: "マラヤーラム数字", text: "൮", kana: "エットゥ", rom: "eṭṭŭ", n: 8, t: 3 },
  { lang: "チベット数字", text: "༩", kana: "グ", rom: "gu", n: 9, t: 3 },
  { lang: "チベット数字", text: "༨", kana: "ギェー", rom: "gyé", n: 8, t: 3 },
  { lang: "クメール数字", text: "៩", kana: "プラムブオン", rom: "pram buən", n: 9, t: 3 },
  { lang: "クメール数字", text: "៨", kana: "プラムバイ", rom: "pram bei", n: 8, t: 3 },
  { lang: "ミャンマー数字", text: "၉", kana: "コー", rom: "kô", n: 9, t: 3 },
  { lang: "ミャンマー数字", text: "၈", kana: "シッ", rom: "shiʔ", n: 8, t: 3 },
  { lang: "ラオ数字", text: "໙", kana: "カーオ", rom: "kao", n: 9, t: 3 },
  { lang: "ラオ数字", text: "໘", kana: "ペート", rom: "pèt", n: 8, t: 3 },
  { lang: "モンゴル文字の数字", text: "᠙", kana: "ユスン", rom: "yesön", n: 9, t: 3 },
  { lang: "モンゴル文字の数字", text: "᠘", kana: "ナイマン", rom: "naiman", n: 8, t: 3 },
  { lang: "ゲエズ数字（エチオピア）", text: "፱", kana: "ゼテニュ", rom: "zeṭeññ", n: 9, t: 3 },
  { lang: "ゲエズ数字（エチオピア）", text: "፰", kana: "スミントゥ", rom: "sïmmïnt", n: 8, t: 3 },
  { lang: "蘇州号碼", text: "〩", kana: "ジウ", rom: "jiǔ", n: 9, t: 3, note: "香港の市場の値札などで使われてきた数字。" },
  { lang: "蘇州号碼", text: "〨", kana: "バー", rom: "bā", n: 8, t: 3 },
  { lang: "キリル数字", text: "ѳ҃", kana: "フィタ", rom: "fita（フィタ）", n: 9, t: 3, note: "古い教会スラヴ語で文字を数字として使った書き方。" },
  { lang: "キリル数字", text: "и҃", kana: "イジェ", rom: "izhe（イジェ）", n: 8, t: 3 },
  { lang: "ギリシャ数字", text: "θʹ", kana: "シータ", rom: "theta（シータ）", n: 9, t: 3 },
  { lang: "ギリシャ数字", text: "ηʹ", kana: "イータ", rom: "eta（イータ）", n: 8, t: 3 },
  { lang: "ヘブライ数字", text: "ט", kana: "テット", rom: "tet（テット）", n: 9, t: 3 },
  { lang: "ヘブライ数字", text: "ח", kana: "ヘット", rom: "chet（ヘット）", n: 8, t: 3 },
  { lang: "点字", text: "⠼⠊", kana: "スウフ・アイ", rom: "数符＋i", n: 9, t: 3 },
  { lang: "点字", text: "⠼⠓", kana: "スウフ・エイチ", rom: "数符＋h", n: 8, t: 3 },
  { lang: "モールス信号", text: "－－－－・", kana: "ツーツーツーツートン", rom: "dah dah dah dah dit", n: 9, t: 3 },
  { lang: "モールス信号", text: "－－－・・", kana: "ツーツーツートントン", rom: "dah dah dah dit dit", n: 8, t: 3 },
  { lang: "二進数", text: "1001", kana: "イチゼロゼロイチ", rom: "8+1", n: 9, t: 3 },
  { lang: "二進数", text: "1010", kana: "イチゼロイチゼロ", rom: "8+2", n: 10, t: 3 },
  { lang: "アイヌ語", text: "sinepesan", kana: "シネペサン", rom: "シネペサン", n: 9, t: 3, note: "「10から1を引く」という作り。" },
  { lang: "アイヌ語", text: "tupesan", kana: "トゥペサン", rom: "トゥペサン", n: 8, t: 3, note: "「10から2を引く」という作り。" },
  { lang: "ズールー語", text: "isishiyagalolunye", kana: "イシシヤガロルニェ", rom: "isishiyagalolunye", n: 9, t: 3, note: "「（指を）1本残す」という意味から。" },
  { lang: "ズールー語", text: "isishiyagalombili", kana: "イシシヤガロンビリ", rom: "isishiyagalombili", n: 8, t: 3, note: "「（指を）2本残す」という意味から。" },
  { lang: "チェロキー語", text: "ᏐᏁᎳ", kana: "ソネラ", rom: "sonela（ソネラ）", n: 9, t: 3 },
  { lang: "チェロキー語", text: "ᏧᏁᎳ", kana: "チュネラ", rom: "tsunela（チュネラ）", n: 8, t: 3 },
  { lang: "ナワトル語", text: "chiucnāhui", kana: "チウクナーウィ", rom: "チウクナーウィ", n: 9, t: 3 },
  { lang: "ナワトル語", text: "chicuēyi", kana: "チクエイ", rom: "チクエイ", n: 8, t: 3 },
  { lang: "ナバホ語", text: "náhástʼéí", kana: "ナハステイ", rom: "ナハステイ", n: 9, t: 3 },
  { lang: "ナバホ語", text: "tseebíí", kana: "ツェービー", rom: "ツェービー", n: 8, t: 3 },
  { lang: "ユカテク・マヤ語", text: "bolon", kana: "ボロン", rom: "ボロン", n: 9, t: 3 },
  { lang: "ユカテク・マヤ語", text: "waxak", kana: "ワシャク", rom: "ワシャク", n: 8, t: 3 },
  { lang: "アイマラ語", text: "llätunka", kana: "リャトゥンカ", rom: "リャトゥンカ", n: 9, t: 3 },
  { lang: "アイマラ語", text: "kimsaqallqu", kana: "キムサカルク", rom: "キムサカルク", n: 8, t: 3 },
  { lang: "古英語", text: "nigon", kana: "ニゴン", rom: "ニゴン", n: 9, t: 3 },
  { lang: "古英語", text: "eahta", kana: "エアハタ", rom: "エアハタ", n: 8, t: 3 },
  { lang: "クリンゴン語", text: "Hut", kana: "フート", rom: "フート", n: 9, t: 3, note: "SF作品『スタートレック』の人工言語。" },
  { lang: "クリンゴン語", text: "chorgh", kana: "チョルグ", rom: "チョルグ", n: 8, t: 3 }
];
