// クイヤゲーム 収録データ
// n   : その語・記号が表す数
// t   : 難易度 (1=やさしい / 2=ふつう / 3=超難問用)
// rom : 読み・ローマ字表記
// note: 豆知識（任意）
// 数字記号は字形の取り違えを避けるため Unicode エスケープで記述しています。
window.QIY_DATA = [
  // ───────── 難易度 1 ─────────
  { lang: "英語", text: "nine", rom: "nine", n: 9, t: 1 },
  { lang: "英語", text: "eight", rom: "eight", n: 8, t: 1 },
  { lang: "ドイツ語", text: "neun", rom: "noin", n: 9, t: 1, note: "「nein（いいえ）」とは別の単語。" },
  { lang: "ドイツ語", text: "zehn", rom: "tsehn", n: 10, t: 1 },
  { lang: "ドイツ語", text: "acht", rom: "acht", n: 8, t: 1 },
  { lang: "フランス語", text: "neuf", rom: "nœf", n: 9, t: 1, note: "「新しい」という意味もある同音異義語。" },
  { lang: "フランス語", text: "huit", rom: "uit", n: 8, t: 1 },
  { lang: "フランス語", text: "dix", rom: "dis", n: 10, t: 1 },
  { lang: "スペイン語", text: "nueve", rom: "nwebe", n: 9, t: 1 },
  { lang: "スペイン語", text: "ocho", rom: "ocho", n: 8, t: 1 },
  { lang: "スペイン語", text: "siete", rom: "siete", n: 7, t: 1 },
  { lang: "イタリア語", text: "nove", rom: "nove", n: 9, t: 1 },
  { lang: "イタリア語", text: "dieci", rom: "dieci", n: 10, t: 1 },
  { lang: "ポルトガル語", text: "oito", rom: "oitu", n: 8, t: 1 },
  { lang: "ポルトガル語", text: "dez", rom: "dez", n: 10, t: 1 },
  { lang: "オランダ語", text: "negen", rom: "neːɣə(n)", n: 9, t: 1 },
  { lang: "オランダ語", text: "tien", rom: "tin", n: 10, t: 1 },
  { lang: "スウェーデン語", text: "nio", rom: "nio", n: 9, t: 1 },
  { lang: "スウェーデン語", text: "tio", rom: "tio", n: 10, t: 1, note: "nio(9) と tio(10) は1文字違い。" },
  { lang: "ラテン語", text: "novem", rom: "novem", n: 9, t: 1, note: "November は古代ローマ暦で「9番目の月」だった。" },
  { lang: "ラテン語", text: "decem", rom: "dekem", n: 10, t: 1, note: "December の語源。古代ローマ暦では10番目の月。" },
  { lang: "ラテン語", text: "octo", rom: "okto", n: 8, t: 1 },
  { lang: "ローマ数字", text: "IX", rom: "10 − 1", n: 9, t: 1 },
  { lang: "ローマ数字", text: "XI", rom: "10 + 1", n: 11, t: 1 },
  { lang: "ローマ数字", text: "VIII", rom: "5 + 3", n: 8, t: 1 },
  { lang: "中国語", text: "九", rom: "jiǔ（ジウ）", n: 9, t: 1 },
  { lang: "中国語", text: "八", rom: "bā（バー）", n: 8, t: 1 },
  { lang: "中国語", text: "六", rom: "liù（リウ）", n: 6, t: 1 },
  { lang: "中国語", text: "七", rom: "qī（チー）", n: 7, t: 1 },
  { lang: "日本語", text: "ここのつ", rom: "kokonotsu", n: 9, t: 1 },
  { lang: "日本語", text: "やっつ", rom: "yattsu", n: 8, t: 1 },
  { lang: "日本語", text: "きゅう", rom: "kyū", n: 9, t: 1 },
  { lang: "日本語", text: "しち", rom: "shichi", n: 7, t: 1 },
  { lang: "韓国語", text: "아홉", rom: "ahop（アホプ）", n: 9, t: 1 },
  { lang: "韓国語", text: "여덟", rom: "yeodeol（ヨドル）", n: 8, t: 1 },
  { lang: "韓国語", text: "열", rom: "yeol（ヨル）", n: 10, t: 1 },
  { lang: "ロシア語", text: "девять", rom: "devyat'（ジェーヴィチ）", n: 9, t: 1 },
  { lang: "ロシア語", text: "десять", rom: "desyat'（ジェーシチ）", n: 10, t: 1, note: "девять(9) と десять(10) はそっくり。" },
  { lang: "ロシア語", text: "восемь", rom: "vosem'（ヴォーシミ）", n: 8, t: 1 },
  { lang: "ギリシャ語", text: "εννέα", rom: "ennéa（エネア）", n: 9, t: 1 },
  { lang: "ギリシャ語", text: "οκτώ", rom: "októ（オクト）", n: 8, t: 1 },
  { lang: "ギリシャ語", text: "δέκα", rom: "déka（デカ）", n: 10, t: 1 },
  { lang: "ベトナム語", text: "chín", rom: "chín（チン）", n: 9, t: 1 },
  { lang: "ベトナム語", text: "tám", rom: "tám（ターム）", n: 8, t: 1 },
  { lang: "インドネシア語", text: "sembilan", rom: "sembilan", n: 9, t: 1 },
  { lang: "インドネシア語", text: "delapan", rom: "delapan", n: 8, t: 1 },
  { lang: "トルコ語", text: "dokuz", rom: "dokuz", n: 9, t: 1 },
  { lang: "トルコ語", text: "sekiz", rom: "sekiz", n: 8, t: 1 },
  { lang: "スワヒリ語", text: "tisa", rom: "tisa", n: 9, t: 1 },
  { lang: "スワヒリ語", text: "saba", rom: "saba", n: 7, t: 1 },
  { lang: "スワヒリ語", text: "nane", rom: "nane", n: 8, t: 1 },
  { lang: "タガログ語", text: "siyam", rom: "siyam", n: 9, t: 1 },
  { lang: "タガログ語", text: "walo", rom: "walo", n: 8, t: 1 },
  { lang: "エスペラント", text: "naŭ", rom: "nau", n: 9, t: 1 },
  { lang: "エスペラント", text: "dek", rom: "dek", n: 10, t: 1 },
  { lang: "ハワイ語", text: "ʻeiwa", rom: "eiwa", n: 9, t: 1 },
  { lang: "ハワイ語", text: "ʻewalu", rom: "ewalu", n: 8, t: 1 },
  { lang: "タイ語", text: "เก้า", rom: "kâo（ガーオ）", n: 9, t: 1 },
  { lang: "タイ語", text: "แปด", rom: "bpàet（ペーット）", n: 8, t: 1 },
  { lang: "ヒンディー語", text: "नौ", rom: "nau（ナウ）", n: 9, t: 1 },
  { lang: "ヒンディー語", text: "आठ", rom: "āṭh（アート）", n: 8, t: 1 },
  { lang: "アラビア語", text: "تسعة", rom: "tisʿa（ティスア）", n: 9, t: 1 },
  { lang: "アラビア語", text: "سبعة", rom: "sabʿa（サブア）", n: 7, t: 1, note: "تسعة(9) と سبعة(7) は点の位置が違うだけ。" },
  { lang: "アラビア文字の数字", text: "٩", rom: "tisʿa", n: 9, t: 1 },
  { lang: "アラビア文字の数字", text: "٨", rom: "thamāniya", n: 8, t: 1 },
  { lang: "アラビア文字の数字", text: "٦", rom: "sitta", n: 6, t: 1 },

  // ───────── 難易度 2 ─────────
  { lang: "フィンランド語", text: "yhdeksän", rom: "yhdeksän", n: 9, t: 2 },
  { lang: "フィンランド語", text: "kahdeksan", rom: "kahdeksan", n: 8, t: 2, note: "yhdeksän(9)とkahdeksan(8)は「10から1/2引く」が由来という説がある。" },
  { lang: "エストニア語", text: "üheksa", rom: "üheksa", n: 9, t: 2 },
  { lang: "エストニア語", text: "kaheksa", rom: "kaheksa", n: 8, t: 2 },
  { lang: "ハンガリー語", text: "kilenc", rom: "kilents", n: 9, t: 2 },
  { lang: "ハンガリー語", text: "nyolc", rom: "nyolts", n: 8, t: 2 },
  { lang: "ポーランド語", text: "dziewięć", rom: "dźewjeńć", n: 9, t: 2 },
  { lang: "ポーランド語", text: "dziesięć", rom: "dźeśeńć", n: 10, t: 2 },
  { lang: "チェコ語", text: "devět", rom: "devjet", n: 9, t: 2 },
  { lang: "チェコ語", text: "deset", rom: "deset", n: 10, t: 2 },
  { lang: "ウクライナ語", text: "дев'ять", rom: "dev'iat'", n: 9, t: 2 },
  { lang: "ウクライナ語", text: "вісім", rom: "visim", n: 8, t: 2 },
  { lang: "ブルガリア語", text: "девет", rom: "devet", n: 9, t: 2 },
  { lang: "ブルガリア語", text: "десет", rom: "deset", n: 10, t: 2 },
  { lang: "クロアチア語", text: "devet", rom: "devet", n: 9, t: 2 },
  { lang: "クロアチア語", text: "osam", rom: "osam", n: 8, t: 2 },
  { lang: "リトアニア語", text: "devyni", rom: "devyni", n: 9, t: 2 },
  { lang: "リトアニア語", text: "dešimt", rom: "dešimt", n: 10, t: 2 },
  { lang: "ラトビア語", text: "deviņi", rom: "deviņi", n: 9, t: 2 },
  { lang: "ラトビア語", text: "astoņi", rom: "astoņi", n: 8, t: 2 },
  { lang: "ルーマニア語", text: "nouă", rom: "nowə", n: 9, t: 2 },
  { lang: "ルーマニア語", text: "zece", rom: "zeche", n: 10, t: 2 },
  { lang: "カタルーニャ語", text: "nou", rom: "nɔw", n: 9, t: 2, note: "「新しい」という意味もある。" },
  { lang: "カタルーニャ語", text: "vuit", rom: "buit", n: 8, t: 2 },
  { lang: "アルバニア語", text: "nëntë", rom: "nëntë", n: 9, t: 2 },
  { lang: "アルバニア語", text: "tetë", rom: "tetë", n: 8, t: 2 },
  { lang: "アイルランド語", text: "naoi", rom: "niː", n: 9, t: 2 },
  { lang: "アイルランド語", text: "ocht", rom: "ocht", n: 8, t: 2 },
  { lang: "ウェールズ語", text: "naw", rom: "nau", n: 9, t: 2 },
  { lang: "ウェールズ語", text: "wyth", rom: "uith", n: 8, t: 2 },
  { lang: "ブルトン語", text: "nav", rom: "nav", n: 9, t: 2 },
  { lang: "ブルトン語", text: "eizh", rom: "eis", n: 8, t: 2 },
  { lang: "アイスランド語", text: "níu", rom: "niːʏ", n: 9, t: 2 },
  { lang: "アイスランド語", text: "tíu", rom: "tʰiːʏ", n: 10, t: 2, note: "níu(9) と tíu(10) は1文字違い。" },
  { lang: "ノルウェー語", text: "ni", rom: "ni", n: 9, t: 2 },
  { lang: "ノルウェー語", text: "ti", rom: "ti", n: 10, t: 2 },
  { lang: "デンマーク語", text: "otte", rom: "ode", n: 8, t: 2 },
  { lang: "アフリカーンス語", text: "nege", rom: "neːχə", n: 9, t: 2 },
  { lang: "アフリカーンス語", text: "agt", rom: "aχt", n: 8, t: 2 },
  { lang: "バスク語", text: "bederatzi", rom: "bederatsi", n: 9, t: 2 },
  { lang: "バスク語", text: "zortzi", rom: "sortsi", n: 8, t: 2 },
  { lang: "ジョージア語", text: "ცხრა", rom: "tskhra（ツフラ）", n: 9, t: 2 },
  { lang: "ジョージア語", text: "რვა", rom: "rva（ルヴァ）", n: 8, t: 2 },
  { lang: "ジョージア語", text: "ათი", rom: "ati（アティ）", n: 10, t: 2 },
  { lang: "アルメニア語", text: "ինը", rom: "inë（イヌ）", n: 9, t: 2 },
  { lang: "アルメニア語", text: "ութ", rom: "utʿ（ウトゥ）", n: 8, t: 2 },
  { lang: "ヘブライ語", text: "תשע", rom: "teshaʿ（テシャ）", n: 9, t: 2 },
  { lang: "ヘブライ語", text: "שבע", rom: "shevaʿ（シェヴァ）", n: 7, t: 2 },
  { lang: "ペルシア語", text: "نه", rom: "noh（ノフ）", n: 9, t: 2 },
  { lang: "ペルシア語", text: "هشت", rom: "hasht（ハシュト）", n: 8, t: 2 },
  { lang: "ペルシア文字の数字", text: "۹", rom: "noh", n: 9, t: 2 },
  { lang: "ペルシア文字の数字", text: "۶", rom: "shesh", n: 6, t: 2 },
  { lang: "ウルドゥー語", text: "نو", rom: "nau（ナウ）", n: 9, t: 2 },
  { lang: "ウルドゥー語", text: "آٹھ", rom: "āṭh（アート）", n: 8, t: 2 },
  { lang: "クルド語", text: "neh", rom: "neh", n: 9, t: 2 },
  { lang: "クルド語", text: "heşt", rom: "hesht", n: 8, t: 2 },
  { lang: "サンスクリット", text: "नव", rom: "nava（ナヴァ）", n: 9, t: 2 },
  { lang: "サンスクリット", text: "अष्ट", rom: "aṣṭa（アシュタ）", n: 8, t: 2 },
  { lang: "デーヴァナーガリー数字", text: "९", rom: "nau", n: 9, t: 2 },
  { lang: "デーヴァナーガリー数字", text: "८", rom: "āṭh", n: 8, t: 2 },
  { lang: "マラーティー語", text: "नऊ", rom: "naū（ナウー）", n: 9, t: 2 },
  { lang: "ベンガル語", text: "নয়", rom: "noy（ノイ）", n: 9, t: 2 },
  { lang: "ベンガル語", text: "আট", rom: "aṭ（アト）", n: 8, t: 2 },
  { lang: "グジャラート語", text: "નવ", rom: "nav（ナヴ）", n: 9, t: 2 },
  { lang: "グジャラート語", text: "આઠ", rom: "āṭh（アート）", n: 8, t: 2 },
  { lang: "パンジャーブ語", text: "ਨੌਂ", rom: "nauṃ（ナウン）", n: 9, t: 2 },
  { lang: "パンジャーブ語", text: "ਅੱਠ", rom: "aṭṭh（アット）", n: 8, t: 2 },
  { lang: "タミル語", text: "ஒன்பது", rom: "oṉpatu（オンバドゥ）", n: 9, t: 2 },
  { lang: "タミル語", text: "எட்டு", rom: "eṭṭu（エットゥ）", n: 8, t: 2 },
  { lang: "テルグ語", text: "తొమ్మిది", rom: "tommidi（トンミディ）", n: 9, t: 2 },
  { lang: "テルグ語", text: "ఎనిమిది", rom: "enimidi（エニミディ）", n: 8, t: 2 },
  { lang: "カンナダ語", text: "ಒಂಬತ್ತು", rom: "ombattu（オンバットゥ）", n: 9, t: 2 },
  { lang: "カンナダ語", text: "ಎಂಟು", rom: "eṇṭu（エントゥ）", n: 8, t: 2 },
  { lang: "マラヤーラム語", text: "ഒമ്പത്", rom: "ompatŭ（オンバトゥ）", n: 9, t: 2 },
  { lang: "マラヤーラム語", text: "എട്ട്", rom: "eṭṭŭ（エットゥ）", n: 8, t: 2 },
  { lang: "シンハラ語", text: "නවය", rom: "navaya（ナワヤ）", n: 9, t: 2 },
  { lang: "シンハラ語", text: "අට", rom: "aṭa（アタ）", n: 8, t: 2 },
  { lang: "モンゴル語", text: "ес", rom: "yes（ユス）", n: 9, t: 2 },
  { lang: "モンゴル語", text: "найм", rom: "naim（ナイム）", n: 8, t: 2 },
  { lang: "カザフ語", text: "тоғыз", rom: "toğyz", n: 9, t: 2 },
  { lang: "カザフ語", text: "сегіз", rom: "segiz", n: 8, t: 2 },
  { lang: "ウズベク語", text: "to'qqiz", rom: "toqqiz", n: 9, t: 2 },
  { lang: "ウズベク語", text: "sakkiz", rom: "sakkiz", n: 8, t: 2 },
  { lang: "アゼルバイジャン語", text: "doqquz", rom: "doqquz", n: 9, t: 2 },
  { lang: "アゼルバイジャン語", text: "səkkiz", rom: "säkkiz", n: 8, t: 2 },
  { lang: "ミャンマー語", text: "ကိုး", rom: "kô（コー）", n: 9, t: 2 },
  { lang: "ミャンマー語", text: "ရှစ်", rom: "shiʔ（シッ）", n: 8, t: 2 },
  { lang: "ラオ語", text: "ເກົ້າ", rom: "kao（カーオ）", n: 9, t: 2 },
  { lang: "ラオ語", text: "ແປດ", rom: "pèt（ペート）", n: 8, t: 2 },
  { lang: "クメール語", text: "ប្រាំបួន", rom: "pram buən（プラム・ブオン）", n: 9, t: 2, note: "「5（プラム）＋4（ブオン）」という作り。" },
  { lang: "クメール語", text: "ប្រាំបី", rom: "pram bei（プラム・バイ）", n: 8, t: 2, note: "「5＋3」という作り。" },
  { lang: "チベット語", text: "དགུ", rom: "gu（グ）", n: 9, t: 2 },
  { lang: "チベット語", text: "བརྒྱད", rom: "gyé（ギェー）", n: 8, t: 2 },
  { lang: "アムハラ語", text: "ዘጠኝ", rom: "zeṭeññ（ゼテニュ）", n: 9, t: 2 },
  { lang: "アムハラ語", text: "ስምንት", rom: "sïmmïnt（スミントゥ）", n: 8, t: 2 },
  { lang: "ソマリ語", text: "sagaal", rom: "sagaal", n: 9, t: 2 },
  { lang: "ソマリ語", text: "siddeed", rom: "siddeed", n: 8, t: 2 },
  { lang: "ハウサ語", text: "tara", rom: "tara", n: 9, t: 2 },
  { lang: "ハウサ語", text: "takwas", rom: "takwas", n: 8, t: 2 },
  { lang: "ヨルバ語", text: "ẹ̀sán", rom: "ɛ̀sán", n: 9, t: 2 },
  { lang: "ヨルバ語", text: "ẹ̀jọ", rom: "ɛ̀dʒɔ", n: 8, t: 2 },
  { lang: "イボ語", text: "itoolu", rom: "itoolu", n: 9, t: 2 },
  { lang: "イボ語", text: "asatọ", rom: "asatɔ", n: 8, t: 2 },
  { lang: "コサ語", text: "lithoba", rom: "litʰoba", n: 9, t: 2 },
  { lang: "コサ語", text: "sibhozo", rom: "sibɦozo", n: 8, t: 2 },
  { lang: "マダガスカル語", text: "sivy", rom: "sivi", n: 9, t: 2 },
  { lang: "マダガスカル語", text: "valo", rom: "valu", n: 8, t: 2 },
  { lang: "マオリ語", text: "iwa", rom: "iwa", n: 9, t: 2 },
  { lang: "マオリ語", text: "waru", rom: "waru", n: 8, t: 2 },
  { lang: "サモア語", text: "iva", rom: "iva", n: 9, t: 2 },
  { lang: "サモア語", text: "valu", rom: "valu", n: 8, t: 2 },
  { lang: "トンガ語", text: "hiva", rom: "hiva", n: 9, t: 2 },
  { lang: "トンガ語", text: "fitu", rom: "fitu", n: 7, t: 2 },
  { lang: "フィジー語", text: "ciwa", rom: "ðiwa", n: 9, t: 2 },
  { lang: "フィジー語", text: "walu", rom: "walu", n: 8, t: 2 },
  { lang: "ジャワ語", text: "sanga", rom: "sɔŋɔ", n: 9, t: 2 },
  { lang: "ジャワ語", text: "wolu", rom: "wolu", n: 8, t: 2 },
  { lang: "ケチュア語", text: "isqun", rom: "isqun", n: 9, t: 2 },
  { lang: "ケチュア語", text: "pusaq", rom: "pusaq", n: 8, t: 2 },
  { lang: "中国語（大字）", text: "玖", rom: "jiǔ", n: 9, t: 2, note: "改ざん防止のため小切手などで使う「大字」。" },
  { lang: "中国語（大字）", text: "捌", rom: "bā", n: 8, t: 2 },
  { lang: "中国語（大字）", text: "柒", rom: "qī", n: 7, t: 2 },
  { lang: "韓国語（漢数詞）", text: "구", rom: "gu（ク）", n: 9, t: 2 },
  { lang: "韓国語（漢数詞）", text: "팔", rom: "pal（パル）", n: 8, t: 2 },
  { lang: "韓国語（漢数詞）", text: "육", rom: "yuk（ユク）", n: 6, t: 2 },
  { lang: "タイ数字", text: "๙", rom: "kâo", n: 9, t: 2 },
  { lang: "タイ数字", text: "๘", rom: "bpàet", n: 8, t: 2 },

  // ───────── 難易度 3（超難問）─────────
  { lang: "ベンガル数字", text: "৯", rom: "noy", n: 9, t: 3 },
  { lang: "ベンガル数字", text: "৪", rom: "car（チャル）", n: 4, t: 3, note: "8に見えるが「4」。" },
  { lang: "タミル数字", text: "௯", rom: "oṉpatu", n: 9, t: 3 },
  { lang: "タミル数字", text: "௮", rom: "eṭṭu", n: 8, t: 3 },
  { lang: "グジャラート数字", text: "૯", rom: "nav", n: 9, t: 3 },
  { lang: "グジャラート数字", text: "૮", rom: "āṭh", n: 8, t: 3 },
  { lang: "オディア数字", text: "୯", rom: "na", n: 9, t: 3 },
  { lang: "オディア数字", text: "୮", rom: "āṭha", n: 8, t: 3 },
  { lang: "テルグ数字", text: "౯", rom: "tommidi", n: 9, t: 3 },
  { lang: "テルグ数字", text: "౮", rom: "enimidi", n: 8, t: 3 },
  { lang: "マラヤーラム数字", text: "൯", rom: "ompatŭ", n: 9, t: 3 },
  { lang: "マラヤーラム数字", text: "൮", rom: "eṭṭŭ", n: 8, t: 3 },
  { lang: "チベット数字", text: "༩", rom: "gu", n: 9, t: 3 },
  { lang: "チベット数字", text: "༨", rom: "gyé", n: 8, t: 3 },
  { lang: "クメール数字", text: "៩", rom: "pram buən", n: 9, t: 3 },
  { lang: "クメール数字", text: "៨", rom: "pram bei", n: 8, t: 3 },
  { lang: "ミャンマー数字", text: "၉", rom: "kô", n: 9, t: 3 },
  { lang: "ミャンマー数字", text: "၈", rom: "shiʔ", n: 8, t: 3 },
  { lang: "ラオ数字", text: "໙", rom: "kao", n: 9, t: 3 },
  { lang: "ラオ数字", text: "໘", rom: "pèt", n: 8, t: 3 },
  { lang: "モンゴル文字の数字", text: "᠙", rom: "yesön", n: 9, t: 3 },
  { lang: "モンゴル文字の数字", text: "᠘", rom: "naiman", n: 8, t: 3 },
  { lang: "ゲエズ数字（エチオピア）", text: "፱", rom: "zeṭeññ", n: 9, t: 3 },
  { lang: "ゲエズ数字（エチオピア）", text: "፰", rom: "sïmmïnt", n: 8, t: 3 },
  { lang: "蘇州号碼", text: "〩", rom: "jiǔ", n: 9, t: 3, note: "香港の市場の値札などで使われてきた数字。" },
  { lang: "蘇州号碼", text: "〨", rom: "bā", n: 8, t: 3 },
  { lang: "キリル数字", text: "ѳ҃", rom: "fita（フィタ）", n: 9, t: 3, note: "古い教会スラヴ語で文字を数字として使った書き方。" },
  { lang: "キリル数字", text: "и҃", rom: "izhe（イジェ）", n: 8, t: 3 },
  { lang: "ギリシャ数字", text: "θʹ", rom: "theta（シータ）", n: 9, t: 3 },
  { lang: "ギリシャ数字", text: "ηʹ", rom: "eta（イータ）", n: 8, t: 3 },
  { lang: "ヘブライ数字", text: "ט", rom: "tet（テット）", n: 9, t: 3 },
  { lang: "ヘブライ数字", text: "ח", rom: "chet（ヘット）", n: 8, t: 3 },
  { lang: "点字", text: "⠼⠊", rom: "数符＋i", n: 9, t: 3 },
  { lang: "点字", text: "⠼⠓", rom: "数符＋h", n: 8, t: 3 },
  { lang: "モールス信号", text: "－－－－・", rom: "dah dah dah dah dit", n: 9, t: 3 },
  { lang: "モールス信号", text: "－－－・・", rom: "dah dah dah dit dit", n: 8, t: 3 },
  { lang: "二進数", text: "1001", rom: "8+1", n: 9, t: 3 },
  { lang: "二進数", text: "1010", rom: "8+2", n: 10, t: 3 },
  { lang: "アイヌ語", text: "sinepesan", rom: "シネペサン", n: 9, t: 3, note: "「10から1を引く」という作り。" },
  { lang: "アイヌ語", text: "tupesan", rom: "トゥペサン", n: 8, t: 3, note: "「10から2を引く」という作り。" },
  { lang: "ズールー語", text: "isishiyagalolunye", rom: "isishiyagalolunye", n: 9, t: 3, note: "「（指を）1本残す」という意味から。" },
  { lang: "ズールー語", text: "isishiyagalombili", rom: "isishiyagalombili", n: 8, t: 3, note: "「（指を）2本残す」という意味から。" },
  { lang: "チェロキー語", text: "ᏐᏁᎳ", rom: "sonela（ソネラ）", n: 9, t: 3 },
  { lang: "チェロキー語", text: "ᏧᏁᎳ", rom: "tsunela（チュネラ）", n: 8, t: 3 },
  { lang: "ナワトル語", text: "chiucnāhui", rom: "チウクナーウィ", n: 9, t: 3 },
  { lang: "ナワトル語", text: "chicuēyi", rom: "チクエイ", n: 8, t: 3 },
  { lang: "ナバホ語", text: "náhástʼéí", rom: "ナハステイ", n: 9, t: 3 },
  { lang: "ナバホ語", text: "tseebíí", rom: "ツェービー", n: 8, t: 3 },
  { lang: "ユカテク・マヤ語", text: "bolon", rom: "ボロン", n: 9, t: 3 },
  { lang: "ユカテク・マヤ語", text: "waxak", rom: "ワシャク", n: 8, t: 3 },
  { lang: "アイマラ語", text: "llätunka", rom: "リャトゥンカ", n: 9, t: 3 },
  { lang: "アイマラ語", text: "kimsaqallqu", rom: "キムサカルク", n: 8, t: 3 },
  { lang: "古英語", text: "nigon", rom: "ニゴン", n: 9, t: 3 },
  { lang: "古英語", text: "eahta", rom: "エアハタ", n: 8, t: 3 },
  { lang: "クリンゴン語", text: "Hut", rom: "フート", n: 9, t: 3, note: "SF作品『スタートレック』の人工言語。" },
  { lang: "クリンゴン語", text: "chorgh", rom: "チョルグ", n: 8, t: 3 }
];
